import { MedicalRecord } from './types';

export const DEMO_SCENARIOS: Record<string, MedicalRecord> = {
  scenario1: {
    isDemoData: true,
    demoLabel: "DEMO DATA — SAMPLE RECORD",
    patient: {
      age: 42,
      sex: "Female",
      symptoms: ["Fatigue", "Shortness of breath on exertion", "Dizziness"],
      existingConditions: ["Mild Asthma"],
      allergies: ["Penicillin"],
      currentMedications: ["Albuterol Inhaler"],
    },
    labResults: [
      {
        id: "demo-101",
        testName: "Hemoglobin",
        value: "9.2",
        numericValue: 9.2,
        unit: "g/dL",
        referenceRange: "12.0 - 15.5",
        rangeMin: 12.0,
        rangeMax: 15.5,
        status: "LOW",
        testDate: "2026-08-20",
        observation: "Microcytic hypochromic red cells observed",
        provenance: "REPORT_EXTRACTED",
        sourceLocation: "Source: Page 1 — Hematology CBC",
        isHumanVerified: false,
      },
      {
        id: "demo-102",
        testName: "White Blood Cell Count (WBC)",
        value: "13.4",
        numericValue: 13.4,
        unit: "10^3/uL",
        referenceRange: "4.5 - 11.0",
        rangeMin: 4.5,
        rangeMax: 11.0,
        status: "HIGH",
        testDate: "2026-08-20",
        observation: "Mild leukocytosis",
        provenance: "REPORT_EXTRACTED",
        sourceLocation: "Source: Page 1 — Hematology CBC",
        isHumanVerified: false,
      },
      {
        id: "demo-103",
        testName: "Platelets",
        value: "250",
        numericValue: 250,
        unit: "10^3/uL",
        referenceRange: "150 - 450",
        rangeMin: 150,
        rangeMax: 450,
        status: "NORMAL",
        testDate: "2026-08-20",
        observation: "Normal morphology",
        provenance: "REPORT_EXTRACTED",
        sourceLocation: "Source: Page 1 — Hematology CBC",
        isHumanVerified: false,
      },
      {
        id: "demo-104",
        testName: "Serum Ferritin",
        value: "8",
        numericValue: 8,
        unit: "ng/mL",
        referenceRange: "15 - 150",
        rangeMin: 15,
        rangeMax: 150,
        status: "LOW",
        testDate: "2026-08-20",
        observation: "Depleted iron stores",
        provenance: "REPORT_EXTRACTED",
        sourceLocation: "Source: Page 2 — Iron Panel",
        isHumanVerified: false,
      },
      {
        id: "demo-105",
        testName: "Vitamin D (25-OH)",
        value: "18",
        numericValue: 18,
        unit: "ng/mL",
        referenceRange: "30 - 100",
        rangeMin: 30,
        rangeMax: 100,
        status: "LOW",
        testDate: "2026-08-20",
        observation: "Vitamin D deficiency",
        provenance: "REPORT_EXTRACTED",
        sourceLocation: "Source: Page 2 — Endocrine Panel",
        isHumanVerified: false,
      },
    ],
    inconsistencies: [
      {
        id: "conflict-abnormal-1",
        title: "Out-of-Range Test Values Noted",
        description: "Potential information conflict — review required: 4 test result(s) fall outside source report reference ranges (Hemoglobin, WBC, Serum Ferritin, Vitamin D).",
        conflictingFields: ["labResults.demo-101", "labResults.demo-102", "labResults.demo-104", "labResults.demo-105"],
      },
    ],
    summary: {
      overview: "Structured review of available patient intake details and laboratory findings dated August 20, 2026.",
      keyObservations: [
        "Patient-reported symptoms include fatigue, dizziness, and exertion-related breathlessness.",
        "Hemoglobin (9.2 g/dL) and Serum Ferritin (8 ng/mL) are below source reference ranges, consistent with microcytic iron deficiency profile.",
        "WBC Count (13.4 10^3/uL) is elevated above source reference range.",
        "Vitamin D level (18 ng/mL) is below the lower reference limit of 30 ng/mL.",
      ],
      disclaimer: "MedLens is an information organization tool. This summary does not constitute a medical diagnosis or treatment plan.",
    },
    metadata: {
      createdAt: new Date().toISOString(),
      reportFileName: "sample_cbc_iron_panel.pdf",
    },
  },

  scenario2: {
    isDemoData: true,
    demoLabel: "DEMO DATA — SAMPLE RECORD",
    patient: {
      age: 58,
      sex: "Male",
      symptoms: ["Routine Health Checkup"],
      existingConditions: ["Hypertension"],
      allergies: ["Sulfa Drugs"],
      currentMedications: ["Lisinopril 10mg"],
    },
    labResults: [
      {
        id: "demo-201",
        testName: "Fasting Blood Glucose",
        value: "98",
        numericValue: 98,
        unit: "mg/dL",
        referenceRange: "70 - 99",
        rangeMin: 70,
        rangeMax: 99,
        status: "NORMAL",
        testDate: "2026-08-15",
        observation: "Normal fasting level",
        provenance: "REPORT_EXTRACTED",
        sourceLocation: "Source: Page 1 — Metabolic Panel",
        isHumanVerified: false,
      },
      {
        id: "demo-202",
        testName: "Serum Creatinine",
        value: "1.1",
        numericValue: 1.1,
        unit: "mg/dL",
        referenceRange: "0.7 - 1.3",
        rangeMin: 0.7,
        rangeMax: 1.3,
        status: "NORMAL",
        testDate: "2026-08-15",
        observation: "Preserved renal function",
        provenance: "REPORT_EXTRACTED",
        sourceLocation: "Source: Page 1 — Metabolic Panel",
        isHumanVerified: false,
      },
      {
        id: "demo-203",
        testName: "High-Sensitivity CRP",
        value: "4.8",
        numericValue: 4.8,
        unit: "mg/L",
        referenceRange: "N/A",
        status: "NOT_PROVIDED",
        testDate: "2026-08-15",
        observation: "No reference range provided in source lab report",
        provenance: "REPORT_EXTRACTED",
        sourceLocation: "Source: Page 2 — Inflammatory Markers",
        isHumanVerified: false,
      },
      {
        id: "demo-204",
        testName: "Urine Protein Dipstick",
        value: "Negative",
        unit: "",
        referenceRange: "None",
        status: "NON_NUMERIC",
        testDate: "2026-08-15",
        observation: "Qualitative dipstick evaluation",
        provenance: "REPORT_EXTRACTED",
        sourceLocation: "Source: Page 2 — Urinalysis",
        isHumanVerified: false,
      },
    ],
    inconsistencies: [],
    summary: {
      overview: "Routine metabolic health panel and urinalysis report dated August 15, 2026.",
      keyObservations: [
        "Fasting Glucose (98 mg/dL) and Serum Creatinine (1.1 mg/dL) are within report reference limits.",
        "High-Sensitivity CRP (4.8 mg/L) was reported without a reference range in the source report and is categorized as 'Not provided'.",
        "Urine Protein Dipstick is recorded as 'Negative' (qualitative result).",
      ],
      disclaimer: "MedLens is an information organization tool. This summary does not constitute a medical diagnosis or treatment plan.",
    },
    metadata: {
      createdAt: new Date().toISOString(),
      reportFileName: "metabolic_urinalysis_report.pdf",
    },
  },

  scenario3: {
    isDemoData: true,
    demoLabel: "DEMO DATA — SAMPLE RECORD",
    patient: {
      age: 35,
      sex: "Female",
      symptoms: ["Sore Throat", "Fever"],
      existingConditions: ["None"],
      allergies: ["Penicillin"],
      currentMedications: ["Acetaminophen"],
    },
    labResults: [
      {
        id: "demo-301",
        testName: "Rapid Strep Test",
        value: "Positive",
        unit: "",
        referenceRange: "Negative",
        status: "NON_NUMERIC",
        testDate: "2026-08-28",
        observation: "Group A Streptococcus antigen detected",
        provenance: "REPORT_EXTRACTED",
        sourceLocation: "Source: Page 1 — Microbiology",
        isHumanVerified: false,
      },
      {
        id: "demo-302",
        testName: "Amoxicillin Note in Previous History",
        value: "250mg BID",
        unit: "mg",
        referenceRange: "N/A",
        status: "NOT_PROVIDED",
        testDate: "2025-04-10",
        observation: "Historical prescription note mentioned in clinical scan",
        provenance: "REPORT_EXTRACTED",
        sourceLocation: "Source: Page 2 — Historical Notes",
        isHumanVerified: false,
      },
    ],
    inconsistencies: [
      {
        id: "conflict-allergy-penicillin-302",
        title: "Potential Medication-Allergy Conflict",
        description: "Potential information conflict — review required: Patient-reported allergy to \"Penicillin\" conflicts with reference to \"Amoxicillin Note in Previous History\" in the report.",
        conflictingFields: ["patient.allergies", "labResults.demo-302"],
      },
    ],
    summary: {
      overview: "Clinical notes and rapid microbiology screening dated August 28, 2026.",
      keyObservations: [
        "Patient-reported symptoms include sore throat and fever, with a reported allergy to Penicillin.",
        "Rapid Strep Test result is Positive.",
        "A historical note references Amoxicillin, which triggers a potential information conflict review relative to the patient's reported Penicillin allergy.",
      ],
      disclaimer: "MedLens is an information organization tool. This summary does not constitute a medical diagnosis or treatment plan.",
    },
    metadata: {
      createdAt: new Date().toISOString(),
      reportFileName: "urgent_care_visit_notes.pdf",
    },
  },
};
